In [1]:
import numpy as np

In [2]:
arr=np.array([2,3,4])

In [3]:
arr

array([2, 3, 4])

In [4]:
arr.ndim

1

In [5]:
arr.shape

(3,)

In [6]:
arr.size

3

In [7]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [8]:
np.arange(1,2,6)

array([1])

In [9]:
np.arange(1,23.5,3)

array([ 1.,  4.,  7., 10., 13., 16., 19., 22.])

In [12]:
np.arange(.1,.2,.006)

array([0.1  , 0.106, 0.112, 0.118, 0.124, 0.13 , 0.136, 0.142, 0.148,
       0.154, 0.16 , 0.166, 0.172, 0.178, 0.184, 0.19 , 0.196])

In [16]:
np.linspace(1,9,3)

array([1., 5., 9.])

In [17]:
np.linspace(1,1,3)

array([1., 1., 1.])

In [18]:
np.linspace(.1,.1,3)

array([0.1, 0.1, 0.1])

In [19]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
d=np.linspace(1,40,40)
d

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40.])

In [45]:
dt=d.reshape(1,2,1,20)
dt

array([[[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
          13., 14., 15., 16., 17., 18., 19., 20.]],

        [[21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
          33., 34., 35., 36., 37., 38., 39., 40.]]]])

In [46]:
for i in dt:
    print(i)

[[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
   18. 19. 20.]]

 [[21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37.
   38. 39. 40.]]]


In [47]:
for i in dt:
    for j in i:
        print(j)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20.]]
[[21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38.
  39. 40.]]


In [48]:
for i in dt:
    for j in i:
        for k in j:
            print(k)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38.
 39. 40.]


In [51]:
arr=np.random.randint(2,6,(3,4))

In [52]:
arr

array([[4, 2, 5, 4],
       [3, 4, 5, 3],
       [3, 4, 2, 3]])

In [53]:
arr[:,[1,3]]

array([[2, 4],
       [4, 3],
       [4, 3]])

In [54]:
arr*arr

array([[16,  4, 25, 16],
       [ 9, 16, 25,  9],
       [ 9, 16,  4,  9]])

In [55]:
a=[2,3,4,4]

In [56]:
a+arr

array([[6, 5, 9, 8],
       [5, 7, 9, 7],
       [5, 7, 6, 7]])

In [57]:
arr+a

array([[6, 5, 9, 8],
       [5, 7, 9, 7],
       [5, 7, 6, 7]])

In [58]:
arr@arr

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [60]:
arr@arr.T

array([[61, 57, 42],
       [57, 59, 44],
       [42, 44, 38]])