In [1]:
import tensorflow as tf

In [2]:
const=tf.constant(34)
const

<tf.Tensor: shape=(), dtype=int32, numpy=34>

In [3]:
const=tf.constant(34,dtype=tf.float)
const

AttributeError: module 'tensorflow' has no attribute 'float'

In [5]:
tf.ones((9,5))

<tf.Tensor: shape=(9, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [6]:
tf.zeros((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [7]:
const1=tf.constant([34,34,45])
const2=tf.constant([3,4,5])
tf.add(const1,const2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([37, 38, 50])>

In [10]:
num=tf.random.normal((3,4
),stddev=1,mean=0
)

In [11]:
tf.reshape(num,[2,6])

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 1.2336982 , -0.19471648, -0.9914694 ,  2.2227974 , -0.09431735,
         0.5356582 ],
       [-1.3190162 , -0.58860356, -0.9965202 ,  1.6724042 , -0.60052496,
         1.2228073 ]], dtype=float32)>

In [19]:
mat1=tf.constant([[3,4,5,6]])
mat2=tf.constant([[4,5,6,6]])

In [18]:
mat1.shape

TensorShape([4])

In [20]:
tf.matmul(mat1,tf.transpose(mat2))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[98]])>

In [21]:
tf.transpose(mat1)@mat2

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[12, 15, 18, 18],
       [16, 20, 24, 24],
       [20, 25, 30, 30],
       [24, 30, 36, 36]])>